### PR TITLE
MediaStream added

### PR DESCRIPTION
**Pull request by morosev**

### CODE REVIEW

**Comment by LoadLibrary** [comment]
@morosev  why do we need this?

**Comment by morosev** [comment]
@LoadLibrary The MediaStream is needed for compatibility with the browsers. SDP negotiation fails if no stream data are recorded in the SDP.

**Comment by jamescadd** [comment]
Just wanted to say thank you @morosev !

**Comment by LoadLibrary** [comment]
Thanks @morosev !

**Pull request merged**
