### PR TITLE
Disable C4826 when including C++/WinRT headers

### PR DESCRIPTION
**Pull request by jehumb-havok**
This breaks building because C++/WinRT does some pointer-to-int64_t cast
which is sign-extended on 32-bit platforms, and generates a warning
C4826 which turns into an error due to /WX.

This fixes webrtc-uwp/webrtc-uwp-sdk#182.

### CODE REVIEW

**Comment by jehumb-havok** [comment]
Updated to only disable C4826 after discussing with @tadam-msft.

**Comment by robin-raymond** [comment]
We left that on intentionally; I wanted to remove all warnings. We have a pre-include header around system headers and webrtc headers to disable specific warnings they generate and for our own warnings I prefer to fix them properly to not have the warning.

**Comment by robin-raymond** [comment]
i.e. for webrtc we do a pre/post include files where we push/pop warnings to disable their problematic files and the same technique can be used for system headers if any cause warnings. I'd rather keep our code clean of everything than remove warnings on the project itself (if possible). Sometimes I know it can't be avoided of course.

**Comment by jehumb-havok** [comment]
There are currently 10 warnings:
- cppwinrt\audiotracksource.h(61)
- cppwinrt\customaudiodevice.h(69)
- cppwinrt\customvideocapturerfactory.h(57)
- cppwinrt\customvideocapturer.h(59)
- cppwinrt\mediastreamtrack.h(74)
- cppwinrt\rtcdtmfsender.h(61)
- cppwinrt\rtcdatachannel.h(69)
- cppwinrt\rtcpeerconnection.h(82)
- cppwinrt\videocapturer.h(57)
- cppwinrt\webrtcfactory.h(71)

It doesn't seem there is any mechanism in place (CI) to prevent those warnings from being introduced in commits, which is problematic.

For the time being, it seems wrapping the newly added includes in `pch.h` does the job of fixing the build, so I guess we can go with that (updated the PR with a change for that only).

**Pull request merged**
